// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA5BYcHhboGfDLb4Iu5depxtpNV021ED0',
    appId: '1:686761649168:web:b4e9d4e6c5b59904e29695',
    messagingSenderId: '686761649168',
    projectId: 'chat-app-54f4e',
    authDomain: 'chat-app-54f4e.firebaseapp.com',
    databaseURL: 'https://chat-app-54f4e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-54f4e.appspot.com',
    measurementId: 'G-C9C96DRZKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_gu1pzRuIMXrXXlDQTvqxac3HRb2yGeg',
    appId: '1:686761649168:android:381e07d84f7932e1e29695',
    messagingSenderId: '686761649168',
    projectId: 'chat-app-54f4e',
    databaseURL: 'https://chat-app-54f4e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-54f4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-cxgXoh3awjrStgG9rAmdp-zCNVoMZHI',
    appId: '1:686761649168:ios:28d658bd4a4aacd4e29695',
    messagingSenderId: '686761649168',
    projectId: 'chat-app-54f4e',
    databaseURL: 'https://chat-app-54f4e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-54f4e.appspot.com',
    iosClientId: '686761649168-trr18he70f6emlakt76nrbvbgflurl1b.apps.googleusercontent.com',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );
}
